apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- keycloak_v1beta1_keycloakinstance.yaml
- keycloak_v1beta1_keycloakrealm.yaml
- keycloak_v1beta1_keycloakclient.yaml
- keycloak_v1beta1_keycloakuser.yaml
- keycloak_v1beta1_keycloakidentityprovidermapper.yaml
