//go:build !ignore_autogenerated

/*
Copyright 2026 HostZero.

Licensed under the BSD 2-Clause License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientAuthSpec) DeepCopyInto(out *ClientAuthSpec) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientAuthSpec.
func (in *ClientAuthSpec) DeepCopy() *ClientAuthSpec {
	if in == nil {
		return nil
	}
	out := new(ClientAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientDefinition) DeepCopyInto(out *ClientDefinition) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.PublicClient != nil {
		in, out := &in.PublicClient, &out.PublicClient
		*out = new(bool)
		**out = **in
	}
	if in.StandardFlowEnabled != nil {
		in, out := &in.StandardFlowEnabled, &out.StandardFlowEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ImplicitFlowEnabled != nil {
		in, out := &in.ImplicitFlowEnabled, &out.ImplicitFlowEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectAccessGrantsEnabled != nil {
		in, out := &in.DirectAccessGrantsEnabled, &out.DirectAccessGrantsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAccountsEnabled != nil {
		in, out := &in.ServiceAccountsEnabled, &out.ServiceAccountsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BearerOnly != nil {
		in, out := &in.BearerOnly, &out.BearerOnly
		*out = new(bool)
		**out = **in
	}
	if in.ConsentRequired != nil {
		in, out := &in.ConsentRequired, &out.ConsentRequired
		*out = new(bool)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebOrigins != nil {
		in, out := &in.WebOrigins, &out.WebOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultClientScopes != nil {
		in, out := &in.DefaultClientScopes, &out.DefaultClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OptionalClientScopes != nil {
		in, out := &in.OptionalClientScopes, &out.OptionalClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AuthorizationServicesEnabled != nil {
		in, out := &in.AuthorizationServicesEnabled, &out.AuthorizationServicesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FullScopeAllowed != nil {
		in, out := &in.FullScopeAllowed, &out.FullScopeAllowed
		*out = new(bool)
		**out = **in
	}
	if in.FrontchannelLogout != nil {
		in, out := &in.FrontchannelLogout, &out.FrontchannelLogout
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientDefinition.
func (in *ClientDefinition) DeepCopy() *ClientDefinition {
	if in == nil {
		return nil
	}
	out := new(ClientDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSecretRefSpec) DeepCopyInto(out *ClientSecretRefSpec) {
	*out = *in
	if in.ClientIdKey != nil {
		in, out := &in.ClientIdKey, &out.ClientIdKey
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretKey != nil {
		in, out := &in.ClientSecretKey, &out.ClientSecretKey
		*out = new(string)
		**out = **in
	}
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSecretRefSpec.
func (in *ClientSecretRefSpec) DeepCopy() *ClientSecretRefSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSecretRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCredentialsSpec) DeepCopyInto(out *ClusterCredentialsSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCredentialsSpec.
func (in *ClusterCredentialsSpec) DeepCopy() *ClusterCredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakInstance) DeepCopyInto(out *ClusterKeycloakInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakInstance.
func (in *ClusterKeycloakInstance) DeepCopy() *ClusterKeycloakInstance {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterKeycloakInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakInstanceList) DeepCopyInto(out *ClusterKeycloakInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterKeycloakInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakInstanceList.
func (in *ClusterKeycloakInstanceList) DeepCopy() *ClusterKeycloakInstanceList {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterKeycloakInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakInstanceSpec) DeepCopyInto(out *ClusterKeycloakInstanceSpec) {
	*out = *in
	out.Credentials = in.Credentials
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(ClientAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(TokenSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakInstanceSpec.
func (in *ClusterKeycloakInstanceSpec) DeepCopy() *ClusterKeycloakInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakInstanceStatus) DeepCopyInto(out *ClusterKeycloakInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakInstanceStatus.
func (in *ClusterKeycloakInstanceStatus) DeepCopy() *ClusterKeycloakInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakRealm) DeepCopyInto(out *ClusterKeycloakRealm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakRealm.
func (in *ClusterKeycloakRealm) DeepCopy() *ClusterKeycloakRealm {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterKeycloakRealm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakRealmList) DeepCopyInto(out *ClusterKeycloakRealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterKeycloakRealm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakRealmList.
func (in *ClusterKeycloakRealmList) DeepCopy() *ClusterKeycloakRealmList {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakRealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterKeycloakRealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakRealmSpec) DeepCopyInto(out *ClusterKeycloakRealmSpec) {
	*out = *in
	if in.InstanceRef != nil {
		in, out := &in.InstanceRef, &out.InstanceRef
		*out = new(NamespacedRef)
		**out = **in
	}
	if in.ClusterInstanceRef != nil {
		in, out := &in.ClusterInstanceRef, &out.ClusterInstanceRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.SmtpSecretRef != nil {
		in, out := &in.SmtpSecretRef, &out.SmtpSecretRef
		*out = new(ClusterSmtpSecretRefSpec)
		**out = **in
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakRealmSpec.
func (in *ClusterKeycloakRealmSpec) DeepCopy() *ClusterKeycloakRealmSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakRealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKeycloakRealmStatus) DeepCopyInto(out *ClusterKeycloakRealmStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKeycloakRealmStatus.
func (in *ClusterKeycloakRealmStatus) DeepCopy() *ClusterKeycloakRealmStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterKeycloakRealmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResourceRef) DeepCopyInto(out *ClusterResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResourceRef.
func (in *ClusterResourceRef) DeepCopy() *ClusterResourceRef {
	if in == nil {
		return nil
	}
	out := new(ClusterResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSecretRefSpec) DeepCopyInto(out *ClusterSecretRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSecretRefSpec.
func (in *ClusterSecretRefSpec) DeepCopy() *ClusterSecretRefSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSecretRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSmtpSecretRefSpec) DeepCopyInto(out *ClusterSmtpSecretRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSmtpSecretRefSpec.
func (in *ClusterSmtpSecretRefSpec) DeepCopy() *ClusterSmtpSecretRefSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSmtpSecretRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentDefinition) DeepCopyInto(out *ComponentDefinition) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentDefinition.
func (in *ComponentDefinition) DeepCopy() *ComponentDefinition {
	if in == nil {
		return nil
	}
	out := new(ComponentDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRepresentation) DeepCopyInto(out *CredentialRepresentation) {
	*out = *in
	if in.Temporary != nil {
		in, out := &in.Temporary, &out.Temporary
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRepresentation.
func (in *CredentialRepresentation) DeepCopy() *CredentialRepresentation {
	if in == nil {
		return nil
	}
	out := new(CredentialRepresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialSecretSpec) DeepCopyInto(out *CredentialSecretSpec) {
	*out = *in
	if in.PasswordPolicy != nil {
		in, out := &in.PasswordPolicy, &out.PasswordPolicy
		*out = new(PasswordPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialSecretSpec.
func (in *CredentialSecretSpec) DeepCopy() *CredentialSecretSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSpec) DeepCopyInto(out *CredentialsSpec) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSpec.
func (in *CredentialsSpec) DeepCopy() *CredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IDPConfigSecretRef) DeepCopyInto(out *IDPConfigSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IDPConfigSecretRef.
func (in *IDPConfigSecretRef) DeepCopy() *IDPConfigSecretRef {
	if in == nil {
		return nil
	}
	out := new(IDPConfigSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialPassword) DeepCopyInto(out *InitialPassword) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialPassword.
func (in *InitialPassword) DeepCopy() *InitialPassword {
	if in == nil {
		return nil
	}
	out := new(InitialPassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRef) DeepCopyInto(out *InstanceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRef.
func (in *InstanceRef) DeepCopy() *InstanceRef {
	if in == nil {
		return nil
	}
	out := new(InstanceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthenticationFlow) DeepCopyInto(out *KeycloakAuthenticationFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthenticationFlow.
func (in *KeycloakAuthenticationFlow) DeepCopy() *KeycloakAuthenticationFlow {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthenticationFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakAuthenticationFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthenticationFlowList) DeepCopyInto(out *KeycloakAuthenticationFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakAuthenticationFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthenticationFlowList.
func (in *KeycloakAuthenticationFlowList) DeepCopy() *KeycloakAuthenticationFlowList {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthenticationFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakAuthenticationFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthenticationFlowSpec) DeepCopyInto(out *KeycloakAuthenticationFlowSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	in.Executions.DeepCopyInto(&out.Executions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthenticationFlowSpec.
func (in *KeycloakAuthenticationFlowSpec) DeepCopy() *KeycloakAuthenticationFlowSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthenticationFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthenticationFlowStatus) DeepCopyInto(out *KeycloakAuthenticationFlowStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthenticationFlowStatus.
func (in *KeycloakAuthenticationFlowStatus) DeepCopy() *KeycloakAuthenticationFlowStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthenticationFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClient) DeepCopyInto(out *KeycloakClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClient.
func (in *KeycloakClient) DeepCopy() *KeycloakClient {
	if in == nil {
		return nil
	}
	out := new(KeycloakClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientList) DeepCopyInto(out *KeycloakClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientList.
func (in *KeycloakClientList) DeepCopy() *KeycloakClientList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScope) DeepCopyInto(out *KeycloakClientScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScope.
func (in *KeycloakClientScope) DeepCopy() *KeycloakClientScope {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeList) DeepCopyInto(out *KeycloakClientScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClientScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeList.
func (in *KeycloakClientScopeList) DeepCopy() *KeycloakClientScopeList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeSpec) DeepCopyInto(out *KeycloakClientScopeSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeSpec.
func (in *KeycloakClientScopeSpec) DeepCopy() *KeycloakClientScopeSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeStatus) DeepCopyInto(out *KeycloakClientScopeStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeStatus.
func (in *KeycloakClientScopeStatus) DeepCopy() *KeycloakClientScopeStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientSpec) DeepCopyInto(out *KeycloakClientSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	if in.ClientId != nil {
		in, out := &in.ClientId, &out.ClientId
		*out = new(string)
		**out = **in
	}
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(ClientSecretRefSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientSpec.
func (in *KeycloakClientSpec) DeepCopy() *KeycloakClientSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientStatus) DeepCopyInto(out *KeycloakClientStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientStatus.
func (in *KeycloakClientStatus) DeepCopy() *KeycloakClientStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakComponent) DeepCopyInto(out *KeycloakComponent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakComponent.
func (in *KeycloakComponent) DeepCopy() *KeycloakComponent {
	if in == nil {
		return nil
	}
	out := new(KeycloakComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakComponent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakComponentList) DeepCopyInto(out *KeycloakComponentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakComponentList.
func (in *KeycloakComponentList) DeepCopy() *KeycloakComponentList {
	if in == nil {
		return nil
	}
	out := new(KeycloakComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakComponentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakComponentSpec) DeepCopyInto(out *KeycloakComponentSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakComponentSpec.
func (in *KeycloakComponentSpec) DeepCopy() *KeycloakComponentSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakComponentStatus) DeepCopyInto(out *KeycloakComponentStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakComponentStatus.
func (in *KeycloakComponentStatus) DeepCopy() *KeycloakComponentStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakGroup) DeepCopyInto(out *KeycloakGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakGroup.
func (in *KeycloakGroup) DeepCopy() *KeycloakGroup {
	if in == nil {
		return nil
	}
	out := new(KeycloakGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakGroupList) DeepCopyInto(out *KeycloakGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakGroupList.
func (in *KeycloakGroupList) DeepCopy() *KeycloakGroupList {
	if in == nil {
		return nil
	}
	out := new(KeycloakGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakGroupSpec) DeepCopyInto(out *KeycloakGroupSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	if in.ParentGroupRef != nil {
		in, out := &in.ParentGroupRef, &out.ParentGroupRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakGroupSpec.
func (in *KeycloakGroupSpec) DeepCopy() *KeycloakGroupSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakGroupStatus) DeepCopyInto(out *KeycloakGroupStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakGroupStatus.
func (in *KeycloakGroupStatus) DeepCopy() *KeycloakGroupStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProvider) DeepCopyInto(out *KeycloakIdentityProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProvider.
func (in *KeycloakIdentityProvider) DeepCopy() *KeycloakIdentityProvider {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakIdentityProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProviderList) DeepCopyInto(out *KeycloakIdentityProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakIdentityProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProviderList.
func (in *KeycloakIdentityProviderList) DeepCopy() *KeycloakIdentityProviderList {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakIdentityProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProviderMapper) DeepCopyInto(out *KeycloakIdentityProviderMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProviderMapper.
func (in *KeycloakIdentityProviderMapper) DeepCopy() *KeycloakIdentityProviderMapper {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakIdentityProviderMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProviderMapperList) DeepCopyInto(out *KeycloakIdentityProviderMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakIdentityProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProviderMapperList.
func (in *KeycloakIdentityProviderMapperList) DeepCopy() *KeycloakIdentityProviderMapperList {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProviderMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakIdentityProviderMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProviderMapperSpec) DeepCopyInto(out *KeycloakIdentityProviderMapperSpec) {
	*out = *in
	in.IdentityProviderRef.DeepCopyInto(&out.IdentityProviderRef)
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProviderMapperSpec.
func (in *KeycloakIdentityProviderMapperSpec) DeepCopy() *KeycloakIdentityProviderMapperSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProviderMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProviderMapperStatus) DeepCopyInto(out *KeycloakIdentityProviderMapperStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProviderMapperStatus.
func (in *KeycloakIdentityProviderMapperStatus) DeepCopy() *KeycloakIdentityProviderMapperStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProviderMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProviderSpec) DeepCopyInto(out *KeycloakIdentityProviderSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	if in.ConfigSecretRef != nil {
		in, out := &in.ConfigSecretRef, &out.ConfigSecretRef
		*out = new(IDPConfigSecretRef)
		**out = **in
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProviderSpec.
func (in *KeycloakIdentityProviderSpec) DeepCopy() *KeycloakIdentityProviderSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakIdentityProviderStatus) DeepCopyInto(out *KeycloakIdentityProviderStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakIdentityProviderStatus.
func (in *KeycloakIdentityProviderStatus) DeepCopy() *KeycloakIdentityProviderStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakIdentityProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakInstance) DeepCopyInto(out *KeycloakInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakInstance.
func (in *KeycloakInstance) DeepCopy() *KeycloakInstance {
	if in == nil {
		return nil
	}
	out := new(KeycloakInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakInstanceList) DeepCopyInto(out *KeycloakInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakInstanceList.
func (in *KeycloakInstanceList) DeepCopy() *KeycloakInstanceList {
	if in == nil {
		return nil
	}
	out := new(KeycloakInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakInstanceSpec) DeepCopyInto(out *KeycloakInstanceSpec) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(ClientAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(TokenSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakInstanceSpec.
func (in *KeycloakInstanceSpec) DeepCopy() *KeycloakInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakInstanceStatus) DeepCopyInto(out *KeycloakInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakInstanceStatus.
func (in *KeycloakInstanceStatus) DeepCopy() *KeycloakInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakOrganization) DeepCopyInto(out *KeycloakOrganization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakOrganization.
func (in *KeycloakOrganization) DeepCopy() *KeycloakOrganization {
	if in == nil {
		return nil
	}
	out := new(KeycloakOrganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakOrganization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakOrganizationList) DeepCopyInto(out *KeycloakOrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakOrganization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakOrganizationList.
func (in *KeycloakOrganizationList) DeepCopy() *KeycloakOrganizationList {
	if in == nil {
		return nil
	}
	out := new(KeycloakOrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakOrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakOrganizationSpec) DeepCopyInto(out *KeycloakOrganizationSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakOrganizationSpec.
func (in *KeycloakOrganizationSpec) DeepCopy() *KeycloakOrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakOrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakOrganizationStatus) DeepCopyInto(out *KeycloakOrganizationStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakOrganizationStatus.
func (in *KeycloakOrganizationStatus) DeepCopy() *KeycloakOrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakOrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakProtocolMapper) DeepCopyInto(out *KeycloakProtocolMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakProtocolMapper.
func (in *KeycloakProtocolMapper) DeepCopy() *KeycloakProtocolMapper {
	if in == nil {
		return nil
	}
	out := new(KeycloakProtocolMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakProtocolMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakProtocolMapperList) DeepCopyInto(out *KeycloakProtocolMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakProtocolMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakProtocolMapperList.
func (in *KeycloakProtocolMapperList) DeepCopy() *KeycloakProtocolMapperList {
	if in == nil {
		return nil
	}
	out := new(KeycloakProtocolMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakProtocolMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakProtocolMapperSpec) DeepCopyInto(out *KeycloakProtocolMapperSpec) {
	*out = *in
	if in.ClientRef != nil {
		in, out := &in.ClientRef, &out.ClientRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientScopeRef != nil {
		in, out := &in.ClientScopeRef, &out.ClientScopeRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakProtocolMapperSpec.
func (in *KeycloakProtocolMapperSpec) DeepCopy() *KeycloakProtocolMapperSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakProtocolMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakProtocolMapperStatus) DeepCopyInto(out *KeycloakProtocolMapperStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakProtocolMapperStatus.
func (in *KeycloakProtocolMapperStatus) DeepCopy() *KeycloakProtocolMapperStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakProtocolMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealm) DeepCopyInto(out *KeycloakRealm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealm.
func (in *KeycloakRealm) DeepCopy() *KeycloakRealm {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmList) DeepCopyInto(out *KeycloakRealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRealm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmList.
func (in *KeycloakRealmList) DeepCopy() *KeycloakRealmList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmSpec) DeepCopyInto(out *KeycloakRealmSpec) {
	*out = *in
	if in.InstanceRef != nil {
		in, out := &in.InstanceRef, &out.InstanceRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterInstanceRef != nil {
		in, out := &in.ClusterInstanceRef, &out.ClusterInstanceRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.SmtpSecretRef != nil {
		in, out := &in.SmtpSecretRef, &out.SmtpSecretRef
		*out = new(SmtpSecretRefSpec)
		**out = **in
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmSpec.
func (in *KeycloakRealmSpec) DeepCopy() *KeycloakRealmSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmStatus) DeepCopyInto(out *KeycloakRealmStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmStatus.
func (in *KeycloakRealmStatus) DeepCopy() *KeycloakRealmStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRequiredAction) DeepCopyInto(out *KeycloakRequiredAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRequiredAction.
func (in *KeycloakRequiredAction) DeepCopy() *KeycloakRequiredAction {
	if in == nil {
		return nil
	}
	out := new(KeycloakRequiredAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRequiredAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRequiredActionList) DeepCopyInto(out *KeycloakRequiredActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRequiredAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRequiredActionList.
func (in *KeycloakRequiredActionList) DeepCopy() *KeycloakRequiredActionList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRequiredActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRequiredActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRequiredActionSpec) DeepCopyInto(out *KeycloakRequiredActionSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRequiredActionSpec.
func (in *KeycloakRequiredActionSpec) DeepCopy() *KeycloakRequiredActionSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRequiredActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRequiredActionStatus) DeepCopyInto(out *KeycloakRequiredActionStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRequiredActionStatus.
func (in *KeycloakRequiredActionStatus) DeepCopy() *KeycloakRequiredActionStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRequiredActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRole) DeepCopyInto(out *KeycloakRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRole.
func (in *KeycloakRole) DeepCopy() *KeycloakRole {
	if in == nil {
		return nil
	}
	out := new(KeycloakRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRoleList) DeepCopyInto(out *KeycloakRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRoleList.
func (in *KeycloakRoleList) DeepCopy() *KeycloakRoleList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRoleMapping) DeepCopyInto(out *KeycloakRoleMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRoleMapping.
func (in *KeycloakRoleMapping) DeepCopy() *KeycloakRoleMapping {
	if in == nil {
		return nil
	}
	out := new(KeycloakRoleMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRoleMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRoleMappingList) DeepCopyInto(out *KeycloakRoleMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRoleMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRoleMappingList.
func (in *KeycloakRoleMappingList) DeepCopy() *KeycloakRoleMappingList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRoleMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRoleMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRoleMappingSpec) DeepCopyInto(out *KeycloakRoleMappingSpec) {
	*out = *in
	in.Subject.DeepCopyInto(&out.Subject)
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(RoleDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleRef != nil {
		in, out := &in.RoleRef, &out.RoleRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRoleMappingSpec.
func (in *KeycloakRoleMappingSpec) DeepCopy() *KeycloakRoleMappingSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRoleMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRoleMappingStatus) DeepCopyInto(out *KeycloakRoleMappingStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRoleMappingStatus.
func (in *KeycloakRoleMappingStatus) DeepCopy() *KeycloakRoleMappingStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRoleMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRoleSpec) DeepCopyInto(out *KeycloakRoleSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	if in.ClientRef != nil {
		in, out := &in.ClientRef, &out.ClientRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRoleSpec.
func (in *KeycloakRoleSpec) DeepCopy() *KeycloakRoleSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRoleStatus) DeepCopyInto(out *KeycloakRoleStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRoleStatus.
func (in *KeycloakRoleStatus) DeepCopy() *KeycloakRoleStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUser) DeepCopyInto(out *KeycloakUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUser.
func (in *KeycloakUser) DeepCopy() *KeycloakUser {
	if in == nil {
		return nil
	}
	out := new(KeycloakUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserCredential) DeepCopyInto(out *KeycloakUserCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserCredential.
func (in *KeycloakUserCredential) DeepCopy() *KeycloakUserCredential {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakUserCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserCredentialList) DeepCopyInto(out *KeycloakUserCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakUserCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserCredentialList.
func (in *KeycloakUserCredentialList) DeepCopy() *KeycloakUserCredentialList {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakUserCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserCredentialSpec) DeepCopyInto(out *KeycloakUserCredentialSpec) {
	*out = *in
	in.UserRef.DeepCopyInto(&out.UserRef)
	in.UserSecret.DeepCopyInto(&out.UserSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserCredentialSpec.
func (in *KeycloakUserCredentialSpec) DeepCopy() *KeycloakUserCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserCredentialStatus) DeepCopyInto(out *KeycloakUserCredentialStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserCredentialStatus.
func (in *KeycloakUserCredentialStatus) DeepCopy() *KeycloakUserCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserList) DeepCopyInto(out *KeycloakUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserList.
func (in *KeycloakUserList) DeepCopy() *KeycloakUserList {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserSpec) DeepCopyInto(out *KeycloakUserSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRealmRef != nil {
		in, out := &in.ClusterRealmRef, &out.ClusterRealmRef
		*out = new(ClusterResourceRef)
		**out = **in
	}
	if in.ClientRef != nil {
		in, out := &in.ClientRef, &out.ClientRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialPassword != nil {
		in, out := &in.InitialPassword, &out.InitialPassword
		*out = new(InitialPassword)
		**out = **in
	}
	if in.UserSecret != nil {
		in, out := &in.UserSecret, &out.UserSecret
		*out = new(UserSecretSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserSpec.
func (in *KeycloakUserSpec) DeepCopy() *KeycloakUserSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserStatus) DeepCopyInto(out *KeycloakUserStatus) {
	*out = *in
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(InstanceRef)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(RealmRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserStatus.
func (in *KeycloakUserStatus) DeepCopy() *KeycloakUserStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedRef) DeepCopyInto(out *NamespacedRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef.
func (in *NamespacedRef) DeepCopy() *NamespacedRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationDefinition) DeepCopyInto(out *OrganizationDefinition) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]OrganizationDomain, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationDefinition.
func (in *OrganizationDefinition) DeepCopy() *OrganizationDefinition {
	if in == nil {
		return nil
	}
	out := new(OrganizationDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationDomain) DeepCopyInto(out *OrganizationDomain) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationDomain.
func (in *OrganizationDomain) DeepCopy() *OrganizationDomain {
	if in == nil {
		return nil
	}
	out := new(OrganizationDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordPolicySpec) DeepCopyInto(out *PasswordPolicySpec) {
	*out = *in
	if in.IncludeNumbers != nil {
		in, out := &in.IncludeNumbers, &out.IncludeNumbers
		*out = new(bool)
		**out = **in
	}
	if in.IncludeSymbols != nil {
		in, out := &in.IncludeSymbols, &out.IncludeSymbols
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordPolicySpec.
func (in *PasswordPolicySpec) DeepCopy() *PasswordPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PasswordPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolMapperDefinition) DeepCopyInto(out *ProtocolMapperDefinition) {
	*out = *in
	if in.ConsentRequired != nil {
		in, out := &in.ConsentRequired, &out.ConsentRequired
		*out = new(bool)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolMapperDefinition.
func (in *ProtocolMapperDefinition) DeepCopy() *ProtocolMapperDefinition {
	if in == nil {
		return nil
	}
	out := new(ProtocolMapperDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmDefinition) DeepCopyInto(out *RealmDefinition) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RegistrationAllowed != nil {
		in, out := &in.RegistrationAllowed, &out.RegistrationAllowed
		*out = new(bool)
		**out = **in
	}
	if in.LoginWithEmailAllowed != nil {
		in, out := &in.LoginWithEmailAllowed, &out.LoginWithEmailAllowed
		*out = new(bool)
		**out = **in
	}
	if in.DuplicateEmailsAllowed != nil {
		in, out := &in.DuplicateEmailsAllowed, &out.DuplicateEmailsAllowed
		*out = new(bool)
		**out = **in
	}
	if in.ResetPasswordAllowed != nil {
		in, out := &in.ResetPasswordAllowed, &out.ResetPasswordAllowed
		*out = new(bool)
		**out = **in
	}
	if in.VerifyEmail != nil {
		in, out := &in.VerifyEmail, &out.VerifyEmail
		*out = new(bool)
		**out = **in
	}
	if in.AccessTokenLifespan != nil {
		in, out := &in.AccessTokenLifespan, &out.AccessTokenLifespan
		*out = new(int32)
		**out = **in
	}
	if in.SsoSessionIdleTimeout != nil {
		in, out := &in.SsoSessionIdleTimeout, &out.SsoSessionIdleTimeout
		*out = new(int32)
		**out = **in
	}
	if in.SsoSessionMaxLifespan != nil {
		in, out := &in.SsoSessionMaxLifespan, &out.SsoSessionMaxLifespan
		*out = new(int32)
		**out = **in
	}
	if in.InternationalizationEnabled != nil {
		in, out := &in.InternationalizationEnabled, &out.InternationalizationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SupportedLocales != nil {
		in, out := &in.SupportedLocales, &out.SupportedLocales
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BruteForceProtected != nil {
		in, out := &in.BruteForceProtected, &out.BruteForceProtected
		*out = new(bool)
		**out = **in
	}
	if in.SmtpServer != nil {
		in, out := &in.SmtpServer, &out.SmtpServer
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmDefinition.
func (in *RealmDefinition) DeepCopy() *RealmDefinition {
	if in == nil {
		return nil
	}
	out := new(RealmDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmRef) DeepCopyInto(out *RealmRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmRef.
func (in *RealmRef) DeepCopy() *RealmRef {
	if in == nil {
		return nil
	}
	out := new(RealmRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleDefinition) DeepCopyInto(out *RoleDefinition) {
	*out = *in
	if in.ClientRef != nil {
		in, out := &in.ClientRef, &out.ClientRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleDefinition.
func (in *RoleDefinition) DeepCopy() *RoleDefinition {
	if in == nil {
		return nil
	}
	out := new(RoleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleMappingSubject) DeepCopyInto(out *RoleMappingSubject) {
	*out = *in
	if in.UserRef != nil {
		in, out := &in.UserRef, &out.UserRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupRef != nil {
		in, out := &in.GroupRef, &out.GroupRef
		*out = new(ResourceRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleMappingSubject.
func (in *RoleMappingSubject) DeepCopy() *RoleMappingSubject {
	if in == nil {
		return nil
	}
	out := new(RoleMappingSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleRepresentation) DeepCopyInto(out *RoleRepresentation) {
	*out = *in
	if in.Composite != nil {
		in, out := &in.Composite, &out.Composite
		*out = new(bool)
		**out = **in
	}
	if in.ClientRole != nil {
		in, out := &in.ClientRole, &out.ClientRole
		*out = new(bool)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleRepresentation.
func (in *RoleRepresentation) DeepCopy() *RoleRepresentation {
	if in == nil {
		return nil
	}
	out := new(RoleRepresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRefSpec) DeepCopyInto(out *SecretRefSpec) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRefSpec.
func (in *SecretRefSpec) DeepCopy() *SecretRefSpec {
	if in == nil {
		return nil
	}
	out := new(SecretRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmtpSecretRefSpec) DeepCopyInto(out *SmtpSecretRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmtpSecretRefSpec.
func (in *SmtpSecretRefSpec) DeepCopy() *SmtpSecretRefSpec {
	if in == nil {
		return nil
	}
	out := new(SmtpSecretRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSpec) DeepCopyInto(out *TokenSpec) {
	*out = *in
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.TokenKey != nil {
		in, out := &in.TokenKey, &out.TokenKey
		*out = new(string)
		**out = **in
	}
	if in.ExpiresKey != nil {
		in, out := &in.ExpiresKey, &out.ExpiresKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSpec.
func (in *TokenSpec) DeepCopy() *TokenSpec {
	if in == nil {
		return nil
	}
	out := new(TokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinition) DeepCopyInto(out *UserDefinition) {
	*out = *in
	if in.EmailVerified != nil {
		in, out := &in.EmailVerified, &out.EmailVerified
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RealmRoles != nil {
		in, out := &in.RealmRoles, &out.RealmRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientRoles != nil {
		in, out := &in.ClientRoles, &out.ClientRoles
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.RequiredActions != nil {
		in, out := &in.RequiredActions, &out.RequiredActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]CredentialRepresentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinition.
func (in *UserDefinition) DeepCopy() *UserDefinition {
	if in == nil {
		return nil
	}
	out := new(UserDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSecretSpec) DeepCopyInto(out *UserSecretSpec) {
	*out = *in
	if in.UsernameKey != nil {
		in, out := &in.UsernameKey, &out.UsernameKey
		*out = new(string)
		**out = **in
	}
	if in.PasswordKey != nil {
		in, out := &in.PasswordKey, &out.PasswordKey
		*out = new(string)
		**out = **in
	}
	if in.GeneratePassword != nil {
		in, out := &in.GeneratePassword, &out.GeneratePassword
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSecretSpec.
func (in *UserSecretSpec) DeepCopy() *UserSecretSpec {
	if in == nil {
		return nil
	}
	out := new(UserSecretSpec)
	in.DeepCopyInto(out)
	return out
}
